browser: chrome
headless: false
viewport:
  width: 1280
  height: 720
environment: qa
device: Desktop Chrome
url: https://example.cypress.io/todo#/
defaultWaitSeconds: 5
report:
  theme: bootstrap # 'bootstrap' or 'simple' or 'foundation' or 'hierarchy'
  json: src/example/resources/reports/results.json
  html: src/example/resources/reports/results.html
  title: Test Summary Report
  launch: true
